### ISSUE TITLE
Documentation on how to run full slow test suite

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2521] opened 2021-05-20 19:04 UTC
We don't have good documentation right now on how to run the full slow test suite. Since this is a core part of our release process we should have a good write-up on the process on the docs

**Comment by arunppsg** [comment] 2021-12-07 16:14
Hey, closing this since documentation on running tests have been added. See [here](https://deepchem.readthedocs.io/en/latest/development_guide/coding.html#unit-tests). Please feel free to reopen it if you think it the issue is not yet addressed. Thanks!

**Closed by arunppsg** 2021-12-07 16:14 UTC
Labels: Good First Contribution, Contribution Welcome
