### ISSUE TITLE
Combine ANITransformer into ANIRegression

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#825] opened 2017-09-05 18:37 UTC
We are working to combine the ANITransformer into the ANIRegressor. The main goals are:

1. Allows for computation of the positional derivative of the potential
2. Allows for the weights of the transformer itself to be optimized
3. Slightly cleaner and easier to maintain code.

The major downside is that it would make it much harder to use the featurization with non ANIRegressor models. Maybe we should consider more generally allowing any transform to be integrated with downstream Tensorgraph layers?

**Comment by lilleswing** [comment] 2017-09-05 18:58
I think the ANI case is a weird one -- ANITransformer is really a featurizer and not a transformer IMO.

I would refactor ANITransformer to utilize a TensorGraph under the hood instead of using raw tensorflow.  Then we can re-use the layers created for other TensorGraphs.

**Comment by proteneer** [comment] 2017-09-06 12:17
I have a crude version of this ready. However, I'm getting NaNs in my gradients w.r.t. x,y,z coordinates. The featurized layer (after applying the BPS functions) itself though does not have NaNs. I suspect there's some discontinuity in the featurization process. Any ideas?

**Comment by rbharath** [comment] 2017-09-06 15:23
This might be a little tricky. We ran into similar issues with the atomic convs. The only debugging mechanism I've had work is to find a minimal example that produces NaNs, then iteratively comment out bits of your TF code till you find the line that produces the NaN. You then want to replace this line with a differentiable proxy.

**Comment by proteneer** [comment] 2017-09-06 15:44
Yeah I'm going through this math this morning to try and figure out what's causing the issue.

**Comment by miaecle** [comment] 2017-09-11 21:39
@proteneer Hi, thanks for posting this and working on the gradient problems. I have actually met with same problem when trying to implement symmetry function methods with trainable cutoffs and parameters. I think ANITransformer is initially implemented as a part of ANIRegression, hence you should be able to find several tensorgraph layer structures in `symmetry_functions.py` that work on building symmetry functions. Moving it out of the model is purely due to speed issue(as well as failing to make it trainable). I am super looking forward to your PR on this, and please let me know if you need any help!

**Comment by rbharath** [comment] 2020-01-18 19:37
Closing this old issue

**Closed by rbharath** 2020-01-18 19:37 UTC
