### ISSUE TITLE
Pip install deepchem installs old version 2.5.0

### ISSUE THREAD

**Issue by rajeshkochi444** [deepchem/deepchem#4153] opened 2024-10-25 13:59 UTC
## 📚 Installation

When I use pip for installing deepchem, it installs 2.5.0 version and when I use for featurezing, it shows tensorflow issue

## Environment

* OS:
* Package manager (PyPI or Conda): pip
* Python version: 3.10/3.12 (tried both)
* DeepChem version: 2.5.0
* TensorFlow version:
* PyTorch version (optional): 2.5.0/2.4.0 
* CUDA/cuDNN version (optional): 12.1
* Any other relevant information:

## Checklist

- [ ] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).

**Comment by shreyasvinaya** [comment] 2024-10-25 16:32
Hi @rajeshkochi444 Could you please provide the exact command you used to install, this is not an intended behaviour

**Comment by rajeshkochi444** [comment] 2024-10-25 16:36
> Hi @rajeshkochi444 Could you please provide the exact command you used to install, this is not an intended behaviour

I discovered the issue was due to the Python version. Initially, I created the environment with Python 3.12, which wasn't compatible, but switching to Python 3.11 allowed DeepChem 2.8.0 to install successfully.

**Comment by shreyasvinaya** [comment] 2024-10-25 16:47
sounds great!, could i close the issue if it was resolved?

**Comment by rajeshkochi444** [comment] 2024-10-25 17:04
Sure

**Closed** 2024-10-25 23:56 UTC
