### ISSUE TITLE
CSVLoader can not load dataset without  task column.

### ISSUE THREAD

**Issue by davidRFB** [deepchem/deepchem#2548] opened 2021-06-11 23:49 UTC
## ❓ Questions & Help
Hi ! 

The CSVLoader requires a task column to create the loader in dataset creation. However, some datasets such as Swissprot will be created to create unsupervised learning models. 

So maybe the class CSVloader should be modified in some way to allow this kind of datasets  ? 
https://github.com/deepchem/deepchem/blob/8cbc6becb2800a156915f2739756867130e9d2ed/deepchem/data/data_loader.py#L267

Thank you very much

**Comment by rbharath** [comment] 2021-06-12 03:58
+1, this would be a good contribution to make to allow for easier loading of unsupervised datasets. This would also be useful for loading datasets for prediction (where we don't have labels)

**Comment by Suzukazole** [comment] 2021-06-14 15:13
@rbharath  this could be potentially relevant for the USPTO loader, as it will use the CSVLoader without a tasks column.

**Comment by davidRFB** [comment] 2021-06-15 00:27
Looking for these feature seems like it is possible to use the CSVloader without tasks just by passing an empty list into the argument: 

```python
data_dir="./"
loader = dc.data.CSVLoader(tasks=[],id_field="ACCNUM",feature_field="SEQUENCE",featurizer=dc.feat.OneHotFeaturizer())
dataset_file = os.path.join(data_dir, "file.csv")
dataset=loader.create_dataset(dataset_file)
```
@rbharath  Maybe just an extra lines in  deepchem/deepchem/data/data_loader.py  documentation will clarify this aspect ?

**Comment by davidRFB** [comment] 2021-06-15 00:35
@Suzukazole Hi ! actually in the work of this issue https://github.com/deepchem/deepchem/issues/1999#issue-654302370  USPTO should be modified to the molnet load function template and the CSV loader could be used.

**Comment by rbharath** [comment] 2021-06-15 05:15
Ah that's good to know! Yes, this looks like a documentation fix rather than a code fix then.

**Comment by arunppsg** [comment] 2021-12-06 17:19
Hey, I tried this code and it seems to work:
```
featurizer = dc.feat.DummyFeaturizer()
df = pd.DataFrame({'num':[1, 2, 3, 4]})
df.to_csv('num.csv')

loader = dc.data.CSVLoader(tasks=[], feature_field="num", featurizer=featurizer)
dataset = loader.create_dataset('num.csv')
```

I was not able to reproduce the error anymore and closing this. Feel free to reopen it if it is required. Thanks!

**Closed by arunppsg** 2021-12-06 17:19 UTC
