### ISSUE TITLE
pandas error in replacing tox21

### ISSUE THREAD

**Issue by sym823808458** [deepchem/deepchem#1519] opened 2019-02-28 07:53 UTC
**Description:**

- DeepChem Version:deepchem 2.10
- Platform:linux Ubuntu

I am trying to replace the tox21 dataset with my own dataset(Zr_dataset).I've changed the datasets quite similar .However when I tried to load mine,some error about pandas occured.
python
```
>>> from __future__ import division
>>> from __future__ import print_function
>>> from __future__ import unicode_literals
>>> 
>>> import numpy as np
>>> import tensorflow as tf
>>> import deepchem as dc
>>> from deepchem.models.tensorgraph.models.graph_models import GraphConvModel
>>> Zr_tasks, Zr_datasets, transformers = dc.molnet.load_Zr(featurizer='GraphConv')

```
Your code sample here
```
Loading raw samples now.
shard_size: 8192
About to start loading CSV from /tmp/Zr.csv.gz
Loading shard 1 of size 8192.
Traceback (most recent call last):
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/molnet/load_function/Zr_datasets.py", line 48, in load_Zr
    dataset = loader.featurize(dataset_file, shard_size=8192)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/data/data_loader.py", line 234, in featurize
    shard_generator(), data_dir, self.tasks, verbose=self.verbose)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/data/datasets.py", line 557, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/data/data_loader.py", line 213, in shard_generator
    X, valid_inds = self.featurize_shard(shard)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/data/data_loader.py", line 256, in featurize_shard
    return featurize_smiles_df(shard, self.featurizer, field=self.smiles_field)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/deepchem/data/data_loader.py", line 63, in featurize_smiles_df
    sample_elems = df[field].tolist()
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'




[whatIadded.zip](https://github.com/deepchem/deepchem/files/2913929/whatIadded.zip)

<!-- You can also ask questions on the DeepChem Gitter
https://gitter.im/deepchem/Lobby
-->

**Comment by VIGS25** [comment] 2019-02-28 08:19
So from the error trace, I can see that the issue is within the set of commands I had asked you to run.
Did you run the commands on the file `~/tmp/Zr.csv.gz` or another copy of the file you have? 

If you look at the code below, which you had posted on the DeepChem gitter, it looks like if the `Zr.csv.gz` file is missing, you end up downloading the `tox21` dataset and the `Zr.csv.gz` actually contains the `tox21` dataset.

```
data_dir = deepchem.utils.get_data_dir()
if reload:
   save_dir = os.path.join(data_dir, "Zr/" + featurizer + "/" + str(split))
   loaded, all_dataset, transformers = deepchem.utils.save.load_dataset_from_disk(save_dir)
if loaded:
 return Zr_tasks, all_dataset, transformers

dataset_file = os.path.join(data_dir, "Zr.csv.gz")
if not os.path.exists(dataset_file):
deepchem.utils.download_url(
'http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/tox21.csv.gz'
)
```

Can you (no-need to repeat if already done) re-run the commands I had suggested on the actual copy of the dataset you have, and make sure the dataset has a smiles field, and let me know what comes out of it?

```
df = pd.read_csv(path_to_file)
field = 'smiles'
sample_elems = df[field].tolist()

print(sample_elems)
```

**Comment by sym823808458** [comment] 2019-02-28 09:32
Thanks a lot,really inspired.I tried the command again and it went wrong similarlily with the error I gave beyond.
In the morning,I copied the Zr.csv from another pile to /tmp/.I tried.Neither of them could run without error.
I loaded a zip contained some part of my Zr.csv beyond.Below is the error occured just now.
```
>>> import pandas as pd
>>> df = pd.read_csv('Zr.csv')
>>> field = 'smiles'
>>> sample_elems = df[field].tolist()
Traceback (most recent call last):
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'
```

**Comment by VIGS25** [comment] 2019-02-28 09:36
Does your file have a `smiles` column in it?
It looks like the most plausible error.

**Comment by sym823808458** [comment] 2019-02-28 09:40
Yes,I do.I printed df.Maybe the problems comes from here.
```
print(df)
   salt  vacuum  SBU  \
0     0       1    0   
1     0       0    1   
2     0       0    0   
3     0       0    0   
4     0       0    0   
5     0       0    0   
6     0       0    0   
7     0       0    0   
8     1       0    0   

  smiles                                                                                                                                                                                                                             
0  O=C(C1=CC=C(C2=CC=C(C(O)=O)S2)S1)O            ...                                                                                                                                                                                 
1  O=C(C1=CC=C(C=C1)C2=CC=C(C=C2)C(C3=CC=C(C=C3)C...                                                                                                                                                                                 
2  CC(C=C1C(C=C2)=CC=C2C(O)=O)=C(C=C1C)C3=CC=C(C=...                                                                                                                                                                                 
3  O=C(C1=CC=C(C=C1)C(O)=O)O                     ...                                                                                                                                                                                 
4  CC(C=C1C(C=C2)=CC=C2C(O)=O)=C(C=C1C)C3=CC=C(C=...                                                                                                                                                                                 
5  CC(C=C1C(C=C2)=CC=C2C(O)=O)=C(C=C1C)C3=CC=C(C=...                                                                                                                                                                                 
6  COC1=C(C2=CC=C(C(O)=O)C=C2)C=C(OC)C(C(C=C3)=CC...                                                                                                                                                                                 
7  O=C(C1=CC=C(C2=CC=C(/C(C3=CC=C(C4=CC=C(C(O)=O)...                                                                                                                                                                                 
8  O=C(C1=CC=C(C2=CC(C)=C(C3=C(C4=C56)C=CC6=C(C7=...      
```
![gkk3tmhqq4b kh oys31p](https://user-images.githubusercontent.com/43782314/53556945-e592cf80-3b7f-11e9-8781-e317e02f96f1.png)

**Comment by VIGS25** [comment] 2019-02-28 09:42
Ah, I see the issue. 
It looks like all your different columns are merged as a single one in the file. 

Maybe you could try fixing that and re-run the method?

**Comment by sym823808458** [comment] 2019-02-28 12:05
Could you please give me some more specific advice?I tried several method but failed.
Thanks.

**Comment by VIGS25** [comment] 2019-02-28 12:09
Your columns should be name `Salt`, `Vaccum`, `SBU` and `smiles`. What it seems to be is `Salt Vaccum SBU Smiles`. (Notice the absence of commas).

If you fix your csv file to have the 4 different columns, then it should work.

**Comment by sym823808458** [comment] 2019-02-28 12:15
![psqcth t7m 4okrxxp r](https://user-images.githubusercontent.com/43782314/53565862-98215d00-3b95-11e9-84cd-9c607a742dfb.png)

**Comment by VIGS25** [comment] 2019-02-28 12:17
What does `df.columns.to_list()` give you?

**Comment by sym823808458** [comment] 2019-02-28 12:34
I am sorry but What do you mean?I am confused.The result is just an error like before.
```
>>> import pandas as pd
>>> df = pd.read_csv('Zr.csv')
>>> print(df)
  smiles                                                                                                                                                                                                         \
0  O=C(C1=CC=C(C2=CC=C(C(O)=O)S2)S1)O            ...                                                                                                                                                              
1  O=C(C1=CC=C(C=C1)C(O)=O)O                     ...                                                                                                                                                              

   vacuum  SBU  
0       1    0  
1       0    0  
>>> field = 'smiles'
>>> sample_elems = df[field].tolist()
Traceback (most recent call last):
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/home/zeng/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'smiles'
```

**Comment by VIGS25** [comment] 2019-02-28 12:37
```
import pandas as pd
df = pd.read_csv('Zr.csv')

print(df.columns.tolist())
```

**Comment by sym823808458** [comment] 2019-02-28 12:40
Wooo!You really got the point!Thanks a lot.I will keep moving forward.
Thanks,Somnath.
![i7eh5pdrkslj6dv u1 vm9u](https://user-images.githubusercontent.com/43782314/53567068-0ddaf800-3b99-11e9-8537-ece5bd6d21a5.png)

**Comment by VIGS25** [comment] 2019-02-28 12:42
If you see, the column name is not actually `smiles`, but instead `smiles` followed by a lot of spaces. Thats why the error keeps coming. Please fix that and the method should run

**Comment by VIGS25** [comment] 2019-03-05 08:24
If this issue is solved, then can you close it?
Feel free to reopen if necessary.

**Closed** 2019-03-05 13:44 UTC
