### ISSUE TITLE
Repeated and/or empty SMILES strings from Sparse featurizer

### ISSUE THREAD

**Issue by rhodos** [deepchem/deepchem#897] opened 2017-10-25 16:29 UTC
I'm trying to extract features from SMILES strings and at the same time, extract labels for each feature (i.e. the SMILES string for each substructure). It seems that, to do this, I need to use the `sparse=True, smiles=True` arguments when defining my featurizer, i.e. something like: `featurizer = dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=False, sparse=True, smiles=True`). However, I'm finding that when I extract features for a single molecule, some of the features have empty SMILES strings, while other SMILES are repeated (see example attached). My guess is that the repeated SMILES strings are due to some collisions of the circular features when translated into SMILES? And that empty SMILES strings correspond to features that do not even translate into SMILES? If so, maybe there is some way that deepchem can handle this?

[example.zip](https://github.com/deepchem/deepchem/files/1415362/example.zip)

**Comment by lilleswing** [comment] 2017-10-25 17:00
```python
import deepchem as dc
import json


def to_numpy_dataset(dataset):
  return dc.data.NumpyDataset(dataset.X, dataset.y, dataset.w, dataset.ids)

dataset_file ="./example_compounds.csv"
tasks = ['dummy_task']

shard_size = 2
feature_size = 1024
radius = 4

#ECFP4
featurizer = dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=False, sparse=True, smiles=True)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
ECFP4 = to_numpy_dataset(loader.featurize(dataset_file, shard_size=shard_size))

# FCFP4
featurizer = dc.feat.CircularFingerprint(radius=radius, size=feature_size, features=True, sparse=True, smiles=True)
loader = dc.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
FCFP4 = to_numpy_dataset(loader.featurize(dataset_file, shard_size=shard_size))


# View features extracted from first compound
print "ECFP4 FINGERPRINT:"
print json.dumps(ECFP4.X[0,], indent=1)

print "\nFCFP4 FINGERPRINT:"
print json.dumps(FCFP4.X[0,], indent=1)
```

**Comment by lilleswing** [comment] 2017-10-25 17:17
The empty SMILES strings are from radius=0 hashes.  There might be issues with off-by-one errors of Chem.FindAtomEnvironment combined with Chem.PathToSubmol.  
```python
    if self.sparse:
      info = {}
      fp = rdMolDescriptors.GetMorganFingerprint(
          mol, self.radius, useChirality=self.chiral,
          useBondTypes=self.bonds, useFeatures=self.features,
          bitInfo=info)
      fp = fp.GetNonzeroElements()  # convert to a dict

      # generate SMILES for fragments
      if self.smiles:
        fp_smiles = {}
        for fragment_id, count in fp.items():
          root, radius = info[fragment_id][0]
          env = Chem.FindAtomEnvironmentOfRadiusN(mol, radius, root)
          frag = Chem.PathToSubmol(mol, env)
          smiles = Chem.MolToSmiles(frag)
          fp_smiles[fragment_id] = {'smiles': smiles, 'count': count}
        fp = fp_smiles
```

As to why other fragments are repeated all I can say is the rdkit MorganFingerprint algorithm considers them different fragments even if they have the same smile string.  Chirality is a possibility here.

**Comment by rhodos** [comment] 2017-10-26 14:08
Thanks for your quick response on this.

"There might be issues with off-by-one errors of Chem.FindAtomEnvironment combined with Chem.PathToSubmol" So you're saying this might be a bug? Or maybe that radius=0 doesn't make sense?

**Comment by lilleswing** [comment] 2017-10-26 14:24
@greglandrum would know what the expected behavior is for the combo -- but what we are seeing is that with radius=0 the fragment returned is an empty string instead of a single atom.  All other cases seem to work fine.

@proteneer if you have any insight into the RDKit inner workings around this.

**Comment by greglandrum** [comment] 2017-10-26 14:25
Short answer: A path is defined by bonds and an environment with radius zero has no bonds.

**Comment by greglandrum** [comment] 2017-10-26 14:26
Is the goal to generate SMILES for a morgan fp bit?

**Comment by rhodos** [comment] 2017-10-26 14:30
@greglandrum Yes, I would like to have a SMILES representation for each bit, or some other representation, if there is something better (i.e. something that wouldn't have collisions).

**Comment by greglandrum** [comment] 2017-10-26 15:06
There's some code in this notebook: https://github.com/greglandrum/rdkit_blog/blob/master/notebooks/Explaining%20Morgan%20Similarity.ipynb
The function you are looking for is `getSubstructSmi()`

I think that's the best that I have managed to put together (and that should land in the RDKit core at some point)

**Comment by rhodos** [comment] 2017-10-26 15:55
Okay thanks, this is helpful.. So maybe for now I should just implement my own version of CircularFingerprint.featurize, incorporating some of the functionality that you have in the notebook?

**Comment by rbharath** [comment] 2018-02-25 06:04
Going to close this issue since I think issues have been addressed. Feel free to re-open if necessary.

**Closed by rbharath** 2018-02-25 06:04 UTC

**Comment by tobiasharren** [comment] 2020-03-05 14:45
Since I needed this function to also output the radius 0 features I inserted some small code, maybe this could be added into the code, since this is more expected behaviour and might be necessary for some interpretation use cases

As some other question, is there a known way to get the fragments associated with bits in the neural fingerprint layer of graph conv networks? (In the Duvenaud Neural Fingerprint paper they extracted the features, but I wasn't able to identify how that worked.)

``  def _featurize(self, mol):
    """
    Calculate circular fingerprint.

    Parameters
    ----------
    mol : RDKit Mol
        Molecule.
    """
    from rdkit import Chem
    from rdkit.Chem import rdMolDescriptors
    if self.sparse:
      info = {}
      fp = rdMolDescriptors.GetMorganFingerprint(
          mol,
          self.radius,
          useChirality=self.chiral,
          useBondTypes=self.bonds,
          useFeatures=self.features,
          bitInfo=info)
      fp = fp.GetNonzeroElements()  # convert to a dict

      # generate SMILES for fragments
      if self.smiles:
        fp_smiles = {}
        for fragment_id, count in fp.items():
          root, radius = info[fragment_id][0]
          if radius == 0:
            atom = mol.GetAtomWithIdx(root)
            aromatic = atom.GetIsAromatic()
            symbol = atom.GetSymbol()
            if aromatic:
                symbol = symbol.lower()
            smiles = "[" + symbol + "]"
          else:
            env = Chem.FindAtomEnvironmentOfRadiusN(mol, radius, root)
            frag = Chem.PathToSubmol(mol, env)
            smiles = Chem.MolToSmiles(frag)
          fp_smiles[fragment_id] = {'smiles': smiles, 'count': count}
        fp = fp_smiles
    else:
      fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(
          mol,
          self.radius,
          nBits=self.size,
          useChirality=self.chiral,
          useBondTypes=self.bonds,
          useFeatures=self.features)
    return fp
