### ISSUE TITLE
About "dc.molnet.load_pdbbind_grid()" I am getting the following some errors

### ISSUE THREAD

**Issue by nbliangying** [deepchem/deepchem#1459] opened 2018-12-03 12:40 UTC
**Description:**
About "dc.molnet.load_pdbbind_grid()" I am getting the following some errors：
PDBBIND_tasks，（train_dataset，valid_dataset，test_dataset），transformers = dc.molnet.load_pdbbind_grid（）

TypeError Traceback (most recent call last)
in ()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid()

TypeError: 'NoneType' object is not iterable

**Comment by VIGS25** [comment] 2018-12-04 18:06
Hi, 
Did you run into the error while trying to run the `protein_ligand_complex` example notebook?

**Comment by nbliangying** [comment] 2018-12-06 13:44
Yes,I run into the error while trying to run the protein_ligand_complex example notebook


 I think this might an indentation error in def load_pdbbind_grid from ~/anaconda3/lib/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py

(..)
if reload:
deepchem.utils.save.save_dataset_to_disk(save_dir, train, valid, test,
transformers)
return tasks, (train, valid, test), transformers

The above return statement is not executed if passing featurizer='grid'.







在2018年12月05 02时07分, "Vignesh Ram Somnath"<notifications@github.com>写道:



Hi,
Did you run into the error while trying to run the protein_ligand_complex example notebook?

**Comment by VIGS25** [comment] 2018-12-07 12:48
Did you install from source or use the conda version?
Because I have it installed from source, and had recently fixed some indentation errors there and didn't have any issues running the notebook, before pushing it

**Comment by nbliangying** [comment] 2018-12-08 01:42
I install from  the pip






在2018年12月07 20时48分, "Vignesh Ram Somnath"<notifications@github.com>写道:



Did you install from source or use the conda version?
Because I have it installed from source, and had recently fixed some indentation errors there and didn't have any issues running the notebook, before pushing it

**Comment by VIGS25** [comment] 2018-12-08 07:18
That explains it.
You can either install from source, to get a working notebook, or else could wait for the new version of DeepChem to be released.

**Comment by nbliangying** [comment] 2018-12-08 13:02
Ok.Thank you very much！






在2018年12月08 15时18分, "Vignesh Ram Somnath"<notifications@github.com>写道:



That explains it.
You can either install from source, to get a working notebook, or else could wait for the new version of DeepChem to be released.

**Comment by VIGS25** [comment] 2018-12-24 11:16
@rbharath: This is sorted now!

**Comment by VIGS25** [comment] 2019-01-16 07:11
@nbliangying: It looks like the issue is resolved. Can you please close it?
Feel free to reopen if necessary

**Comment by nbliangying** [comment] 2019-01-16 13:06
OK!

Thank you very much!






在2019年01月16 15时11分, "Vignesh Ram Somnath"<notifications@github.com>写道:



@nbliangying: It looks like the issue is resolved. Can you please close it?
Feel free to reopen if necessary

**Closed** 2019-01-16 13:07 UTC
Labels: bug, help wanted
