### ISSUE TITLE
model.save() NotImplementedError

### ISSUE THREAD

**Issue by amazing-rando** [deepchem/deepchem#1710] opened 2019-11-16 01:12 UTC
- DeepChem Version: 2.3.0
- Platform: Linux Mint

When trying to save a trained model, I receive an error which states that this feature is not implemented.  The version of DeepChem that I installed is the gpu version.

The error message that I get is as follows:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-21-ea3f7cf76c70> in <module>
      1 #Fit model using all available data and then save it.
      2 #model.fit(data)
----> 3 model.save()

~/miniconda3/lib/python3.7/site-packages/deepchem/models/models.py in save(self)
    107     Each subclass is responsible for overriding this method.
    108     """
--> 109     raise NotImplementedError
    110 
    111   def fit(self, dataset, nb_epoch=10, batch_size=50, **kwargs):

NotImplementedError: 
```

Below is the code that results in the above error:

```
import deepchem as dc
from deepchem.models import GraphConvModel

loader = dc.data.CSVLoader(tasks = ["is_active"],
                           smiles_field = "SMILES",
                           featurizer = dc.feat.ConvMolFeaturizer())
data = loader.featurize("./data/mapk1.csv", shard_size = 8192)

def make_graph_conv_model(batch_size,
                          dense_layer_size = 128,
                          dropout = [0.0, 0.0, 0.0],
                          graph_conv_layers = [64, 64],
                          number_atom_features = 75,
                          model_dir = "./models"):
    '''
    For a given batch size, define and return a graph convolutional
    model.
    '''
    model = GraphConvModel(1,
                           batch_size = batch_size,
                           mode = "classification",
                           dense_layer_size = dense_layer_size,
                           dropout = dropout,
                           graph_conv_layers = graph_conv_layers,
                           number_atom_features = number_atom_features,
                           model_dir = model_dir)

    return model

model = make_graph_conv_model(batch_size = 128)

#Fit model using all available data and then save it.
model.fit(data)
model.save()
```

Is there perhaps another method of saving a model or is this functionality currently broken in this version of DeepChem?

**Comment by VIGS25** [comment] 2019-11-17 13:25
`model.save_checkpoint()` is what you're looking for. That said, saving is also done by default during training and after training is complete.

**Comment by oguitart** [comment] 2019-11-18 15:22
Duplicate of #1705

**Comment by rbharath** [comment] 2020-01-16 17:33
See the discussion in #1729. TL;DR, `model.save()` is no longer required and auto-save should work. There are some possible issues with autosave we're working on in #1705. Feel free to join the discussion there. Going to close this issue for now

**Closed by rbharath** 2020-01-16 17:33 UTC
