### ISSUE TITLE
model.save() raises an error NotImplemented

### ISSUE THREAD

**Issue by JZuegg** [deepchem/deepchem#1729] opened 2020-01-16 01:37 UTC
Hi, 

- DeepChem Version: 2.3.0

I am starting to use DeepChem, after 1 year break, and I am trying to run some old scripts of mine from dc 2.1, in the current **dc 2.3.0** version. Specifically, I am trying to run a model=dc.models.MultitaskClassifier model, but when the script tries to _model.save()_:
**error NotImplemented** 

In the 'old' version, model.save created a 'model.pickle' file, which could be checked for if a model was present in a certain folder, before _model.load_from_dir(model_dir)_. In dc 2.30, the folder only contains checkpoint files 

Thanks for any help...

**Comment by rbharath** [comment] 2020-01-16 02:56
Interesting, this could be a bug in the latest release. I'm going to mark this as a bug and see if I can reproduce. I'm doing a lot of general DeepChem planning so might take me a bit to get to this.

@peastman Do you have any thoughts in the meanwhile?

**Comment by JZuegg** [comment] 2020-01-16 03:51
Just realized .. has been rasied in #1705 and #1710

**Comment by peastman** [comment] 2020-01-16 17:24
It's not a bug: the `save()` method just doesn't exist anymore.  In early versions of DeepChem you had to call `save()` on your model to save the fitted parameters.  But for a long time now it has automatically saved parameters while fitting, so you can just remove that line.

**Comment by rbharath** [comment] 2020-01-16 17:31
Ah good point! @JZuegg I'm going to close this issue since it's not a bug, but feel free to re-open if necessary.

**Closed by rbharath** 2020-01-16 17:31 UTC
Labels: Contribution Welcome, bug
