### ISSUE TITLE
one-shot examples in version 1.3.1

### ISSUE THREAD

**Issue by YangBingjiao** [deepchem/deepchem#1021] opened 2018-01-10 08:53 UTC
Hi,

I am using the version 1.3.1 and notice that the one-shot learning examples are deprecated. So would you mind telling me the new APIs or new functions for one-shot learning?

Thanks so much & best regards,
Yang Bingjiao

**Comment by rbharath** [comment] 2018-01-10 23:26
Good question. We're still working on this. For now, I'd recommend checking out `dc.meta` which implements an alternate meta-learning/one-shot algorithm. We plan to port the original one-shot algorithm into `dc.meta`

**Comment by YangBingjiao** [comment] 2018-01-12 00:37
Thanks a lot, Dr. rbharath. I will try it later and I suggest that you give priority to the development of one-shot learning because it may be the predominant feature of deepchem.

**Comment by YangBingjiao** [comment] 2018-01-12 00:39
@rbharath Thanks a lot, Dr. Ramsundar. I will try it later and I suggest that you give priority to the development of one-shot learning because it may be the predominant feature of deepchem.

**Comment by rbharath** [comment] 2018-01-12 00:41
Fair enough. It's definitely an important feature that adds a lot of value.

Btw, we would love developer support for adding in better one-shot algorithms and porting over the legacy implementations. I'm adding the "contributions welcome tag" to this issue. Let's use it to track progress. Feel free to ping me in a few weeks if nothing has happened.

**Comment by YangBingjiao** [comment] 2018-01-16 00:47
@rbharath Thanks so much, Dr. Ramsundar.

**Comment by rbharath** [comment] 2018-01-16 01:13
Re-opening this issue so we can use it to track progres.

**Comment by sanjaradylov** [comment] 2019-03-29 11:20
Hi, @rbharath . I am interested in implementing one-shot models presented in [Low Data Drug Discovery with One-shot Learning](https://arxiv.org/abs/1611.03199) paper.
I am having difficulties using one-shot models from deepchem 1.3.1. I tried to run examples from [low_data](https://github.com/deepchem/deepchem/tree/1.3.1/examples/low_data) package on my own data, but faced run-time errors. After considerations, I thought it would be more convenient to re-implement these models, particularly support estimators and sequential graphs. Some research on this issue led me here, and there seems to be no progress on solving it.
Can you please explain why the models were removed and how you were planning to port them over? Was there any particular architecture different from [tf_new_models](https://github.com/deepchem/deepchem/tree/1.3.1/deepchem/models/tf_new_models) considered for one-shot models?

**Comment by rbharath** [comment] 2019-03-29 20:26
Unfortunately I just haven't had the bandwidth to port these models. I'd be glad to help support any reimplementation efforts. I'd recommend using TensorGraph instead of the old tf_new_models. Feel free to ask questions on this thread

**Comment by ikramov** [comment] 2019-06-19 15:43
Hello, I would like to use Low Data for regression models not the classification.
Could you help with that? Do you have already implemented examples of using one shot for regression?

**Comment by rbharath** [comment] 2019-06-19 17:53
Unfortunately one-shot regression is trickier than one-shot classification. The one-shot classification methods work by basically doing a nearest-neighbors type algorithm for classification. It ought to be possible to port to a nearest neighbors regression, but it will take some work

**Comment by rbharath** [comment] 2020-02-27 00:13
I'm closing this issue since we don't currently have plans to port the "Low Data Drug Discovery Paper." The main reason for this is that the techniques from that paper are a little outdated now (there's been lots of work on meta learning in the last few years) and I'd rather we focus on implementing the best meta learning system from the current literature rather than the older work. Feel free to comment here if you think we should keep this issue open.

**Closed by rbharath** 2020-02-27 00:13 UTC
Labels: Contribution Welcome
