### ISSUE TITLE
Simplify TensorGraph API

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#498] opened 2017-04-01 01:48 UTC
I'm finding the TensorGraph API kind of cumbersome to work with.  This is mainly because you have to call `add_layer()` for every layer, which forces you to create a variable for every layer.  For example, suppose `a` and `b` are two layers.  As your loss function, you want to multiply them together and take the mean of all elements.  (This is a real example I came across.  `a` contains the cost function for every task, and `b` is the weights.)  Currently, you have to write something like this:

```Python
graph.add_layer(a)
graph.add_layer(b)
mult = Multiply()
graph.add_layer(mult, parents=[a,b])
reducemean = ReduceMean()
graph.add_layer(reducemean, parents=[mult])
graph.set_loss(reducemean)
```

I suggest getting rid of `add_layer()`.  You would only need to tell the graph about layers that have special roles, like with `set_loss()` or `add_output()`.  The parents of each layer would be passed as arguments to its constructor.  With this change, the above code could be simplified to

```Python
graph.set_loss(ReduceMean(Multiply(a, b)))
```

**Comment by rbharath** [comment] 2017-04-01 02:22
Hmm, this is an interesting suggestion. The current structure of `TensorGraph` uses `add_layer()` to add nodes to the underlying graph structure for the model. While it is admittedly a little cumbersome, it gives us the power to construct arbitrary graph structures (arbitrary DAG to be precise). Once the graph structure is constructed, it's linearized, and the layers are called in bottom-up order to add the ops to the underlying tensorflow graph belonging to the model object.

As I understand it, this proposal is close to the [Keras functional API](https://keras.io/getting-started/functional-api-guide/). This API requires no explicit add calls, but the downside is that layers are evaluated in the scope of the default graph. If users want to prevent this, they have to explicitly manage Tensorflow graphs, which is painful.

The tradeoff seems then to be between the more onerous `add_layer`, which allows for neat hiding away of Tensorflow graphs, or the more free functional API, which exposes graphs to the user. I'm currently leaning towards `add_layer` since requiring users to deal with the underlying Tensorflow graph seems like a leaky abstraction.

Perhaps there's a nice intermediate design that works around these limitations though. Would love to hear your thoughts @peastman and @lilleswing

**Comment by peastman** [comment] 2017-04-01 02:48
I don't see the connection.  I'm not suggesting any change to how it would do computations.  You could still construct arbitrary DAGs, and you wouldn't need to directly interact with the underlying Tensorflow objects.  This is just a simplification to the API.

The main point is that we don't actually gain anything by calling `add_layer()`.  The graph can already discover every layer in the graph just by tracing backward from the outputs.

**Comment by rbharath** [comment] 2017-04-01 19:12
This is a good point. I think I understand what you're getting at now.

Let me summarize what I understand of the proposal. I believe the key change required would be that the constructors for layers would take on the responsibility for getting the parents for that given layer. `add_layer` does this right now and stores all parent information in the `TensorGraph`, but the modification would store parent information within the layers themselves. Then, the `TensorGraph` would be responsible for tracing backwards and constructing the DAG and evaluating the DAG to add tensorflow ops to its graph. All tensorflow ops building would remain within the `__call__` methods for layers, which should stay unchanged.

@peastman Is this a correct summary?

In general, I like this proposed change. This would make our code look very similar to Keras's functional API, which is probably the cleanest deep network code style out there. As a bonus, we don't lose the tight control over the Tensorflow graphs that we need.

@lilleswing Does the proposed design change look reasonable to you? Are there any failure cases we might run into?

**Comment by peastman** [comment] 2017-04-01 22:54
That's exactly what I had in mind.

**Comment by lilleswing** [comment] 2017-04-03 17:15
These changes sound good to me.

One thing that I would want to take into account when we change the API is handling of sharing weights.  The current architecture does not support it, and we know we have multiple architectures with sharing weights coming up.  

I would prefer to make this change only if we can also see how it can handle "sharing" a layer between multiple inputs/outputs.

Keras solves this by the object you are creating when called twice shares the weights.
https://keras.io/getting-started/functional-api-guide/#shared-layers

**Comment by peastman** [comment] 2017-04-03 17:31
If I understand that example, the Keras API treats layers as function objects?  And instead of passing the parents to the constructor, you invoke the object and pass the parents then?  So instead of `Multiply(a, b)`, you would write `Multiply()(a, b)`?

That's one way of doing it, though I find it a little obtuse.  It creates a confusing distinction between the layer itself and the result of invoking the layer.  An alternative would be for each layer to have a `shared()` method to create a shared copy with different parents.  So following their example of two LSTM layers with shared weights, you would write

```Python
lstm1 = LSTM(parent1)
lstm2 = lstm1.shared(parent2)
```

That keeps the API simpler for the most common case (not shared weights), and makes it clear where you do share weights.  Another option would be to have a `Shared` layer that does the same thing:

```Python
lstm1 = LSTM(parent1)
lstm2 = Shared(lstm1, parent2)
```

**Comment by lilleswing** [comment] 2017-04-03 18:05
I like 
```python
lstm2 = lstm1.shared(parent2)
```

Then its each layers responsibility to allow sharing (the technical details will not come for free for any given layer.

**Comment by peastman** [comment] 2017-04-03 18:11
Now that I've read that Keras example, I think I understand some aspects of TensorGraph better that were confusing me before.  Like why you create the Tensorflow objects in `__call__()` instead of a private method like `_create_tensor()`.  I see now you were copying that from Keras.

We should decide what kind of API this is supposed to be.  Is it an API for creating Tensorflow objects, and those objects are explicitly exposed to the user?  If so, then making layers callable makes sense.  Though in that case, why don't we just use the Keras layers rather than creating our own versions that do the same thing?  On the other hand, if the layers are supposed to be opaque objects, and the Tensorflow objects are an implementation detail that's hidden from the user, using a private method would make more sense.

**Comment by rbharath** [comment] 2017-04-03 18:24
Keras layers are very complicated under the hood. Part of this is due to Keras's support for both Theano and Tensorflow back-ends. This dual support necessitates multiple abstractions that make back-end Keras code pretty difficult to work with. The current minimal `Layer` objects in `TensorGraph` are much nicer to build on.

I like the idea of making Tensorflow objects that are explicitly exposed to users. There are a lot of new research layers in DeepChem and ideally users should be able to mix DeepChem `Layer` objects with custom Tensorflow code as desired.

@lilleswing Does the current `TensorGraph` API support shared layers?

**Comment by lilleswing** [comment] 2017-04-03 18:27
@rbharath it does not -- but it is a necessity to get the current work from Atomic Convs in.
https://arxiv.org/abs/1703.10603

I just thought to be less disruptive we should include a change which adds the power of sharing weights at the same time.

**Comment by lilleswing** [comment] 2017-04-03 18:29
@peastman the way I see it is an API which lets the user create Tensorflow objects which are Graph Scoped.

The API should also take care of issues for the user like 
1. Saving/Restoring
2. Feeding in Data
3. Evaluation

**Comment by peastman** [comment] 2017-04-03 18:30
> I like the idea of making Tensorflow objects that are explicitly exposed to users.

Ok, that's reasonable.  We still might want to consider creating them with a named method like `create_tensor()`, though.  The idea that a layer is a function doesn't seem very intuitive to me, and it's not at all obvious that calling it will return a Tensorflow object.

**Comment by lilleswing** [comment] 2017-04-03 18:35
@peastman yeah that was my thought when I was making it as well :) (Explicitly making it a create_tensor() instead of __call__ and then making the user create a lambda).  I think the reason we decided it was fine is because its already a design pattern in other libraries. 

We should document it more because it is unintuitive though.

**Comment by rbharath** [comment] 2017-04-03 18:46
Thinking about this, here are a couple points to figure out:

1. In both the current/proposed setup, the parents of layers are other layers. How can a DeepChem layer be invoked in pure Tensorflow code where the parents will just be Tensors?
2. Should we remove `__call__()`? In the new design, the parents are passed into the constructor and invoking a layer via function-call like Keras is less meaningful. Perhaps we should just have a `create_tensor()` or `build()` method that adds the layer to the graph in scope and remove `__call__()`.

@peastman, @lilleswing Would love your thoughts here

**Comment by peastman** [comment] 2017-04-03 19:00
> How can a DeepChem layer be invoked in pure Tensorflow code where the parents will just be Tensors?

How about a `Tensor` layer class that wraps an arbitrary tensor and allows it to be passed as a parent?  That would let you use a layer in Tensorflow code, but it would not work correctly going in the other direction (using an arbitrary tensor in a TensorGraph), so the graph should throw an exception if it sees you've tried to use one.

**Comment by rbharath** [comment] 2017-04-03 19:33
Ok, here's an summary of design changes for a `TensorGraph` API Change:

1. Remove `TensorGraph.add_layer()`. Move responsibility for getting parents to the contructors of `Layer` objects.
2. Retain functions like `TensorGraph.set_loss(layer)` or `TensorGraph.add_output(layer)` to tell `TensorGraph` what the outputs from the model are (make sure to support GANs, which have 2 different losses). 
3. Add `Layer.shared(parents)` method which allows for weight-sharing between layers. For example, `lstm2 = lstm1.shared(parents2)`. Each layer takes on responsibility for implementing its own `shared(parents)` method since weights differ depending on the layer.
4. Make it possible to invoke `Layer` objects on Tensorflow tensors (so DeepChem code can be easily used with pure Tensorflow Code). Perhaps via use of a `Tensor` layer class as @peastman suggests above.
5. Remove `Layer.__call__()` and replace with `Layer.create_tensors()` that adds tensors to the graph currently in scope.

@lilleswing Does this API change look good? If so, would you be game to take on the refactor? You have the best knowledge of the `TensorGraph` code :-)

**Comment by peastman** [comment] 2017-04-03 20:39
> (make sure to support GANs, which have 2 different losses).

Maybe replace `set_loss()` with `add_loss()`?  Then when you call `fit()`, you specify which loss to use.  If there's only one loss you can omit that argument.  But if there are multiple losses, I suggest the argument should be required.  Arbitrarily picking one of them if the argument is omitted would create opportunities for bugs.

Then again, implementing GANs might take something a little more complicated than that.  You have to tell it not just which loss to use, but also which parameters to optimize and which to hold fixed.

**Comment by lilleswing** [comment] 2017-04-03 20:40
@rbharath , @peastman I'm not sure if (4) is possible.

 under the hood tensorflow instantiation of a Tensor is a mutative effect on the global graph.  It would not work unless you are already scoped in the graph of the Model.

It would have to be a lambda which gets executed while inside the appropriate Graph Scope.

**Comment by lilleswing** [comment] 2017-04-03 20:43
@peastman , were you thinking of setting the following objects on the model
1. outputs
2. inputs
3. loss
4. weights

Then after all were set and _build was called internally doing a flood fill algorithm from outputs and loss, and verifying that the graph included all inputs and weights?

**Comment by peastman** [comment] 2017-04-03 21:09
Is it necessary to add inputs and weights?  Or can those also be determined automatically?  For example, is there a case where the set of `Input` layers contained in the graph is different from the set passed to `add_input()`?  If the two could be different, we need to distinguish them in some way.  But if they'll always be the same, it's not necessary.

**Comment by lilleswing** [comment] 2017-04-03 21:12
@peastman would you suggest differentiating between Inputs and Weights via Layer Class?

**Comment by rbharath** [comment] 2017-04-03 21:57
@peastman I like the idea of `add_loss()` and having `fit()` accept a loss as an argument (if there's only one loss available, no need to specify). I think this should be enough for GAN training.

@lilleswing We can punt on this on (4) for this PR. Advanced users can always copy-paste code from the repo

**Comment by rbharath** [comment] 2017-04-03 22:00
@peastman @lilleswing I think weights can just be a type of `Input`. The weights are placeholders just like labels in the current multitask tensorflow code.

**Comment by rbharath** [comment] 2017-04-04 08:05
Here's an example of what a 2-hidden layer fully connected network would look like under the new API.

```
# Define Layers
in = Input((32, 1024))
h1 = Dense(64, in)
h2 = Dense(64, h1)
logits = Dense(1, h2)
loss = SoftmaxCrossEntropy(logits)
out = Softmax(logits)

# Define Model
model = TensorGraph()
model.add_input(in)
model.add_output(out)
model.add_loss(loss)
model.fit()
```

Looks pretty slick. Having `add_input()`, `add_output()`, and `add_loss()` methods in `TensorGraph` should let us control the 3 types of inputs needed by `TensorGraph`

**Comment by lilleswing** [comment] 2017-04-04 15:48
@rbharath labels now just a type of input?  Then a user will have to sometimes override _construct_feed_dict which takes (X_b, y_b, w_b) and put it in the correct tensors based on the lists of inputs.

**Comment by peastman** [comment] 2017-04-04 16:38
How will dropout fit into this?  Will it be built into each layer, or will there be a separate layer to do it?

**Comment by lilleswing** [comment] 2017-04-04 16:44
@peastman I think dropout works best as a layer, and then maybe also as an arg to common layers (i.e. dense)

**Comment by rbharath** [comment] 2017-04-04 17:40
@lilleswing I see what you mean. I think it would be nice to support the generic `add_input()`, but that might require more work. Let's just keep `add_features()`, `add_labels()`, `add_weights()` for now so making feed dictionaries doesn't become hard.

**Comment by rbharath** [comment] 2017-04-04 17:42
Updated version of example:

```
# Define Layers
features = Input((32, 1024))
labels = Input((32, 1))
h1 = Dense(64, features)
h2 = Dense(64, h1)
logits = Dense(1, h2)
loss = SoftmaxCrossEntropy(logits, labels)
out = Softmax(logits)

# Define Model
model = TensorGraph()
model.add_features(features)
model.add_labels(labels)
model.add_output(out)
model.add_loss(loss)
model.fit(dataset)
```

Still pretty slick :-)

**Comment by lilleswing** [comment] 2017-04-04 20:32
Yeah this looks good I can make the changes.

**Comment by peastman** [comment] 2017-04-04 23:19
After thinking about this a bit more, it seems to me it would be better to have three different classes for features, labels, and weights.  In the design above, you use the `Input` class for all three.  But the graph needs to know which are which to build the feed dict, so that requires having the `add_feature()`, `add_label()`, and `add_weight()` methods.  Instead, I suggest having separate `Feature`, `Label`, and `Weight` layers.

This has a couple of advantages.  It makes the code a bit more concise, since you don't need to call the `add_x()` methods.  I think it will also be more readable.  When you see the following, it's obvious at a glance what the role of `y` is in the graph:

```Python
y = Label()
```

In contrast, this is less obvious and takes a little more work to decipher:

```Python
y = Input()
graph.add_label(y)
```

It takes even more work if those two lines get separated from each other, so `add_label()` doesn't get called until a while after the layer is created.

**Comment by rbharath** [comment] 2017-04-04 23:25
@peastman I like the proposal. Then only `add_output()` and `add_loss()` are required since `TensorGraph` can unambiguously figure out the labels/weights from the source nodes.

**Comment by rbharath** [comment] 2017-04-04 23:25
Updated Design:


```
# Define Layers
features = Features((32, 1024))
labels = Labels((32, 1))
h1 = Dense(64, features)
h2 = Dense(64, h1)
logits = Dense(1, h2)
loss = SoftmaxCrossEntropy(logits, labels)
out = Softmax(logits)

# Define Model
model = TensorGraph()
model.add_output(out)
model.add_loss(loss)
model.fit(dataset)
```

**Comment by rbharath** [comment] 2017-04-06 01:51
#505 shows a weakness in the current design: We can't properly handle graphs with multiple input placeholders. Most of the more complicated models (DTNNs, DAGs, Weaves, ACNNs) require multiple input placeholders. Writing custom `construct_feed_dict()` methods for each is going to get painful.

To deal with the issue in general, I have a proposed API change for `fit()`. Here are two API calls which `fit()` would support in the new API:

Suppose we have a model as follows:

```
# Define Layers
features_1 = Features((32, 1024))
features_2 = Features((32, 512))
labels = Labels((32, 1))
out = Dense(64, Concat(features_1, features_2))
loss = L2Loss(out, labels)

# Define Model
model = TensorGraph()
model.add_output(out)
model.add_loss(loss)
```

1. `model.fit(dataset)`: current API will continue to work as always.
2. `model.fit({features_1: dataset_1, features_2: dataset_2, labels: dataset_labels})`: Change `fit()` to accept a dictionary whose keys are layers and whose values are datasets. `dataset_1.X` will contain the `(N, 1024)` features. `dataset_2.X` will contain the `(N, 512)` features. `dataset_3.y` will contain the labels.

This design should let us handle arbitrary placeholders by passing in appropriate dictionaries. It will require us to change the featurizers to return multiple `dataset` for the different input placeholders, but this should be a straightforward fix.

**Comment by rbharath** [comment] 2017-04-06 02:31
For fun, tried converting @lilleswing's `TensorGraph` graph-convs to proposed API:
```
atom_features = Features((None, 75))
degree_slice = Features((None, 2), tf.int32)
membership = Features((None,), tf.int32)

deg_adjs = []
for i in range(model.min_degree, model.max_degree + 1):
  deg_adj = Features((None, i + 1), tf.int32)
  deg_adjs.append(deg_adj)
graph_features = [degree_slice, membership] + deg_adjs

gc1 = GraphConvLayer(64, tf.nn.relu, [atom_features] + graph_features)
bn1 = BatchNormLayer(gc1)
gp1 = GraphPoolLayer([bn1] + graph_features)
gc2 = GraphConvLayer(64, tf.nn.relu, [gp1] + graph_features)
bn2 = BatchNormLayer([gc2] + graph_features)
gp2 = GraphPoolLayer([bn2] + deg_ads)
dense = Dense(128, None, gp2)
bn3 = BatchNormLayer(dense)
gg1 = GraphGather(batch_size, tf.nn.tanh, [bn3] + graph_features)

labels, costs = [], []
for task in range(num_tasks):
  classification = Dense(2, gg1)
  softmax = SoftMax(classification)
  model.add_output(softmax)

  label = Labels((None, 2))
  cost = SoftMaxCrossEntropy(label, classification)
  labels.append(label)
  costs.append(cost)

entropy = Concat(costs)
task_weights = Weights((None, num_tasks))
loss = WeightedError(entropy, task_weights)

model = TensorGraph(batch_size=batch_size, use_queue=False)
model.add_loss(loss)
# Assume this contains a list of datasets, one per placeholder, output by Featurizer
all_datasets = (featurization call)
model.fit(dict(zip([atom_features] + graph_features + labels + [task_weights], all_datasets)))
```

Looks pretty slick! The new graph-convs are almost as concise as the original, but don't hide all the placeholders under the hood like the original implementation did.

We might want to add something like a `MultiTaskOutputs()` layer which adds the output heads. This will likely be a shared primitive for many models, so probably worth making easy.

**Comment by rbharath** [comment] 2017-04-06 17:42
@peastman @lilleswing Would love your thoughts on whether the design makes sense!

@miaecle Would this proposed design be enough to implement the newer models like DTNN, DAGs, and other?

**Comment by rbharath** [comment] 2017-04-06 19:09
@lilleswing pointed out on #505 that this wouldn't quite be enough for graph-convs since we dynamically generate per-batch information. Here's a proposed extra API function:

```
model.fit_generate(dict_generator)
```

Here `dict_generator` is a python generator which generates dictionaries of the form `{features_1: dataset_1, features_2: dataset_2, labels: dataset_labels}` (or whatever), one for each batch. This is essentially a public-facing version of `construct_feed_dict()` and should let the user make arbitrary training regimens.

@lilleswing Would this suffice?

**Comment by lilleswing** [comment] 2017-04-06 19:12
Yeah it should suffice -- I'll still try to make it easier for the default case of 1 feature, 1 label, 1 weight.

**Comment by miaecle** [comment] 2017-04-06 19:41
@rbharath Thanks for all your hard work. New codes look extremely simple and nice. I believe all graph-based models(DTNN, DAG, weave) should have basically the same requirements as graphconv. Will try to get them on Tensorgraph

**Comment by rbharath** [comment] 2017-04-14 05:02
With the new `TensorGraph` API implemented by @lilleswing in #517, I think the API looks much smoother. Here are some of the next TODOs on continuing API work:

- Implement `Layer.shared()` in order to facilitate models with weight sharing, like atomic convs.
  - @lilleswing Interested in taking this one on?
- Add utility functions (or new layers) that take make adding multi-task heads a one-line call rather than a complicated for-loop.
  - @peastman Up for this one?
- Start converting MoleculeNet, one-shot, and atomic-conv models over to `TensorGraph`. 
  - @miaecle Interested in converting the MoleculeNet models?

For my part, I'll be working on porting the autodock-vina/docking models into `TensorGraph`

**Comment by miaecle** [comment] 2017-04-14 06:48
@rbharath Definitely, I can take it.

**Comment by peastman** [comment] 2017-04-14 15:24
Sure.

**Comment by lilleswing** [comment] 2017-04-14 17:42
yeah I'm doing it as part of putting atomic convs in mainline.

https://github.com/lilleswing/deepchem/pull/13

**Comment by cxhernandez** [comment] 2017-05-03 20:18
Hopefully this request fits in with this discussion: Would it be possible to have `TensorGraph` models inherit from sklearn's [`BaseEstimator`](http://scikit-learn.org/stable/modules/generated/sklearn.base.BaseEstimator.html)? This would allow for more interoperability with tools like [Osprey](https://github.com/msmbuilder/osprey/issues/219).

@rbharath mentioned in Slack that:

> The issue is that DeepChem uses custom Dataset objects to process datasets that don't fit in memory
> We have methods almost like BaseEstimator but slightly different as a result

This does present some challenges, but I imagine we could wrap some checks in `fit` and `predict` that can distinguish between Dataset objects and raw data.

**Comment by rbharath** [comment] 2017-05-04 03:19
I think I'm generally open to these changes. We have `dc.hyper` for hyperparameter selection, but that's pretty much deprecated at this point. Integrating with Osprey would provide a consistent API for doing model hyperparameter searching, which we lack right now. I think this will take a bit of work to get right, but would be very valuable.

**Comment by lilleswing** [comment] 2017-05-04 14:56
Can functionality be added to Osprey for
https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Evaluable

and

https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Trainable

as these API are in tensorflow contrib they are likely going to become more widespread.  They also allow for taking in iterators to deal with larger datasets.

**Comment by cxhernandez** [comment] 2017-05-04 17:54
Yeah, if TF already has a nice API to follow, then I think we should probably go with that. 

Ideally, we'd have something that's sklearn-compatible so that models/transformer can be chained together across deepchem, sklearn, and msmbuilder with [`Pipeline`](http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) objects.

From my tinkering, I think the biggest thing missing for this is a consistent API for scoring models (e.g. `TensorGraph.score(X, y=y)`). Right now, Osprey only handles a single score since that's all we've needed in our use-cases. For deepchem users, are multiple metrics absolutely necessary when evaluating a model or could you just live with correlation (for regression problems) and accuracy (for classification problems)?

One idea I had is to just make the metric a settable parameter in the class, which could then used in `score` but also have the option to use the `evaluate` method to score over multiple metrics once you have your desired model.

**Comment by rbharath** [comment] 2017-05-04 20:23
I like the idea of following TF's lead where possible. 

Support for different metrics is pretty key for MoleculeNet. We should ideally let users optimize with respect to an arbitrary `Metric` that they define.

**Comment by rbharath** [comment] 2018-02-17 17:13
This discussion is pretty old at this point so closing the issue.

**Closed by rbharath** 2018-02-17 17:13 UTC
