### ISSUE TITLE
How can I provide a validation dataset to a regressor for use during training?

### ISSUE THREAD

**Issue by gufodotto** [deepchem/deepchem#308] opened 2016-12-08 09:54 UTC
Hi deepchem-ers, 
thanks to you all for making this available to the community. I have a question, and am not sure this is the right place to ask it.

I can't manage to run the delaney regressor example (load_delaney will not be found, even when I change to that directory and add . to sys.path(). Regardless, I've cooked my own version of it, and that runs fine. However, r2 performances on the training set is markedly different from that in the validation set. In my previous experience with keras, performances on the two track each other rather well. 

Here, though: 
Train scores {'mean-pearson_r2_score': 0.92440806049359725}
Validation scores {'mean-pearson_r2_score': 0.37968515682972304}
Test  scores {'mean-pearson_r2_score': 0.31459100674679491}

It seems to me like the validation set, albeit generated in the splitting procedure, isn't actually used during training. Am I missing something?

**from deepchem/models/tensorflow_models/__init__.py:**
> def fit(self, dataset, nb_epoch=10, pad_batches=False, 
>           max_checkpoints_to_keep=5, log_every_N_batches=50, **kwargs):
> 

KR,

    Luca

**Comment by rbharath** [comment] 2016-12-08 20:02
@gufodotto Great to see that you're experimenting with DeepChem!

Yes, that's right that the validation dataset isn't used during training. The `fit` method only performs gradient descent on the training dataset. The validation dataset can be used to perform hyperparameter tuning (see `dc.hyper`), but we don't currently support early stopping or other methods that would use validation data during training.

Your numbers on `delaney` look a little different from our benchmark numbers:

|Dataset    |Model               |Splitting   |Train score/R2|Valid score/R2|
|-----------|--------------------|------------|--------------|--------------|
|delaney    |MT-NN regression    |Index       |0.773         |0.574         |
|           |MT-NN regression    |Random      |0.769         |0.591         |
|           |MT-NN regression    |Scaffold    |0.782         |0.426         |

How did you try running the Delaney example? Running `python delaney_tf_models.py` from within `examples/delaney` should (almost exactly) reproduce the Index split numbers from the table above.

**Comment by gufodotto** [comment] 2016-12-08 21:15
Thanks @rbharath, that explains the lack of influence of the validation set.

As for running the delaney examples, two issues here. First of all, the numbers posted are obtained from our own in house data points, not the delaney outcome. I meant them to show how the validation set isn't being used.

Second, I just tried again and failed, in the same way.

**(DL3.5) c182437@brainiac-ia-0001:1157$ $REDACTED/DeepLearning/deepchem/examples/delaney**
 **_python ./delaney_tf_models.py_**
/lrlhps/users/c182437/bin/anaconda3/envs/DL3.5/lib/python3.5/site-packages/rdkit/Chem/PeriodicTable.py:131: FutureWarning: split() requires a non-empty pattern match.
  splitLine = blankExpr.split(line)
Using TensorFlow backend.
Traceback (most recent call last):
  File "./delaney_tf_models.py", line 12, in <module>
    from delaney_dataset import load_delaney
ImportError: No module named 'delaney_dataset'
 even if 
**(DL3.5) c182437@brainiac-ia-0001:1157$ $REDACTED/DeepLearning/deepchem/examples/delaney**
**_ls ._**
**delaney_datasets.py**  delaney_tf_models.py  delaney_tf_progressive.py  __init__.py
it's definitely there. Oh, I get it now. It's named delaney_dataset'_**s**_'.py, whereas the code looks for 'delaney_dataset.

I fixed that and it runs:
Train scores
{'mean-pearson_r2_score': 0.87695250267596125}
Validation scores
{'mean-pearson_r2_score': 0.54362137776897113}

**Comment by rbharath** [comment] 2016-12-08 23:49
@gufodotto Good find about `delaney_datasets`. Just started a bugfix PR for that now.

**Comment by rbharath** [comment] 2016-12-09 01:11
@gufodotto If you'd like better performance on validation/test sets, I'd recommend experimenting with graph-convolutions. They seem to offer better performance overall. I'm going to go ahead and close this issue since I don't believe the remaining issue is a model tuning issue, and not a bug. Feel free to open more issues if you run into other problems!

**Closed by rbharath** 2016-12-09 01:11 UTC

**Comment by gufodotto** [comment] 2016-12-09 08:41
Excellent, I was indeed looking to start working with graph-convolutions.
I hope the examples on low_data are current - they seem to run, but they're
based on kera and my understanding from reading your issues is that you're
removing keras dependencies because of their switch to a functional API.
Thanks again for your help. Much appreciated

   Luca

**Comment by rbharath** [comment] 2016-12-10 18:24
@gufodotto All examples (except those in `broken/` folder) are current and run. I am planning to remove the Keras dependencies, but I will keep all examples functional during the crossover. Feel free to use the `low_data/` examples for work.
