### ISSUE TITLE
`n_features` not required when using customized featurizer in `dc.molnet.run_benchmark`

### ISSUE THREAD

**Issue by XericZephyr** [deepchem/deepchem#453] opened 2017-03-09 05:32 UTC
@miaecle  As the title indicates, `n_features` is not required when using customized featurizer in `run_benchmark` function. 

We might need an abstract redesign for `benchmark_regression`, but for a quick fix, I can try to fix it in a **dirty way** by setting it to `None`.

**Comment by miaecle** [comment] 2017-03-09 06:45
Thanks for raising the issue! I do notice this tricky `n_features` issue, difficulty here is that it has different meaning in different models. 
Most of the deepchem models require this parameter in the input(except for rf and irv). I suggest you to add it manually(dirty way), though we may try to seek a way to circumvent it.

**Comment by miaecle** [comment] 2017-03-09 07:10
#454 n_features is initialized now, need to redefine when using user-defined featurizers with deepchem models(multitask network, logistic regression, etc.)

**Comment by rbharath** [comment] 2017-03-13 18:29
@miaecle, @XericZephyr: Can we close this issue?

**Comment by miaecle** [comment] 2017-03-13 19:22
@rbharath Yeah I think so, the issue is covered in the PR #454

**Closed** 2017-03-13 19:23 UTC
