### ISSUE TITLE
Support make_estimator() for all models

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1142] opened 2018-03-07 21:49 UTC
Most subclasses of TensorGraph will need changes before `make_estimator()` will work with them.  Anything that overrides `default_generator()` definitely will.  I already made the necessary changes to `MultiTaskRegressor` and `MultiTaskClassifier`.  I also looked at `MultiTaskFitTransformRegressor`, but concluded it probably can't be supported without significant changes to how transformers work.

Here is a list of all TensorGraph subclasses.  (If I missed anything, let me know.)  We can check off each one once we've either modified it to work, or concluded it isn't practical to do that.

- [x] MultiTaskRegressor
- [x] MultiTaskClassifier
- [x] MultiTaskFitTransformRegressor
- [ ] TensorflowMultiTaskIRVClassifier
- [x] GAN
- [ ] WeaveTensorGraph
- [ ] DTNNTensorGraph
- [ ] DAGTensorGraph
- [ ] PetroskiSuchTensorGraph
- [ ] GraphConvTensorGraph
- [ ] MPNNTensorGraph
- [x] SeqToSeq
- [ ] BPSymmetryFunctionRegression
- [ ] ANIRegression
- [ ] TextCNNTensorGraph
- [x] ProgressiveMultitaskRegressor
- [x] RobustMultitaskClassifier
- [x] RobustMultitaskRegressor
- [x] Sequential

To support a class, here's what needs to be done.  First, add a test case for it in test_estimators.py.  You may be able to adapt code from one of the other test cases.  The tutorial from #1136 may also be helpful.

In most cases the test will fail with an error saying the class overrides `default_generator()` but not `create_estimator_inputs()`.  So now you need to override `create_estimator_inputs()` to do whatever special manipulations `default_generator()` is doing, only with Tensorflow operators instead of numpy.

The job of `create_estimator_inputs()` is to create a dict where the keys are all of the model's input layers, and the values are the tensors to use for them.  Here is what the default implementation looks like.  Notice that it supports an arbitrary number of `Feature` layers, but only one `Weights` and one `Label` layer.  That's because of limitations in how estimators work.

```python
    tensors = {}
    for layer, column in zip(self.features, feature_columns):
      tensors[layer] = tf.feature_column.input_layer(features, [column])
    if weight_column is not None:
      tensors[self.task_weights[0]] = tf.feature_column.input_layer(
          features, [weight_column])
    if labels is not None:
      tensors[self.labels[0]] = tf.cast(labels, self.labels[0].dtype)
    return tensors
```

Consider `MultiTaskClassifier`.  It overrides `default_generator()` to convert the labels from class indices into one-hot encoded values:

```python
feed_dict[self.labels[0]] = to_one_hot(y_b.flatten(),
                                       self.n_classes).reshape(
                                           -1, self.n_tasks,
                                           self.n_classes)
```

It therefore overrides `create_estimator_inputs()` and modifies it to likewise convert the labels to one-hot:

```python
tensors[self.labels[0]] = tf.one_hot(
    tf.cast(labels, tf.int32), self.n_classes)
```

**Comment by rbharath** [comment] 2018-03-08 00:12
I'm marking this a good intermediate level contribution. If you're interested in taking on part of the needed implementation work, please leave a comment here indicating the class(es) you're converting. Please follow @peastman's implementation guide above, and open a pull request marked "[WIP]" tracking your on-going implementation efforts.

**Comment by peastman** [comment] 2018-03-10 01:56
I've checked off `GAN` and `SeqToSeq` as not practical to adapt.  They both add their own fit and predict methods that do a lot of extra work.  Creating an Estimator from them would require defining an Estimator subclass that similarly adds a lot of logic to fitting and prediction.

**Comment by peastman** [comment] 2018-03-11 23:49
I'm working on RobustMultiTaskRegressor, RobustMultiTaskClassifier, and Sequential.

**Comment by peastman** [comment] 2018-03-12 17:24
Sequential is complicated because the model isn't fully defined until you call `fit()` on it.  The main reason that was done is so that you don't have to define the sizes of the inputs in advance.  That isn't a problem here, since they'll be defined by the arguments to `create_estimator()`.  But it also has the strange feature that the loss is defined by an argument to `fit()`.  Is there a reason for that?  Could we make the loss be an argument to the constructor instead?

Note that the current API allows you to call `fit()` twice and specify a different loss each time—but the second time, it silently ignores the value you pass and uses the loss from the first call instead.  I'd call that a bug.

**Comment by rbharath** [comment] 2018-03-13 18:41
@peastman I was attempting to keep the Sequential API as close to the Keras API as I could manage. That said, I think it's reasonable to fix up the API so that it behaves cogently.

How about making the loss something that's added explicitly via an `add_loss()` call? Adding in the constructor seems awkward since the loss would be added before all the layers.

Agree that the behavior of `fit()` is a bug that should be fixed.

**Comment by peastman** [comment] 2018-03-13 19:27
For Sequential, the loss is a string with only two allowed values: `mse` or `binary_crossentropy`.  So `add_loss()` doesn't seem like quite the right API.  You're not adding anything, just selecting between two options.

**Comment by rbharath** [comment] 2018-03-23 18:06
The discussion in https://github.com/deepchem/deepchem/pull/1151 suggests that it's not currently feasible to add estimator support for TensorGraph models with submodels. As a result, `ProgressiveMultitaskClassifier` and `ProgressiveMultitaskRegressor` currently lack estimator support.

**Comment by VIGS25** [comment] 2018-10-17 09:58
I'd like to work on the TextCNN TensorGraph.
WIP Pull Request [here](https://github.com/deepchem/deepchem/pull/1434)

**Comment by VIGS25** [comment] 2019-01-01 15:36
Ping @peastman @rbharath. 
Also a Happy New Year!

**Comment by peastman** [comment] 2019-01-02 00:11
I don't have any good ideas about this, but maybe @rbharath can suggest something.  We would need to take the object and do all the same calculations as in `default_generator()`,  but entirely with TensorFlow operations.  I don't know if that's even possible.

**Comment by VIGS25** [comment] 2019-01-02 00:18
For the graph models, I tried out `tf.py_func` over the numpy calculations that a `default_generator()` does and it did the processing needed, but `Dataset.make_iterator()` fails because it expects `X` to have a `dtype`.

**Comment by VIGS25** [comment] 2019-01-06 19:41
Yes I agree to that.
But the error is of the form `object of type Mol has no attribute dtype`. `make_iterator` looks at a single `(X, y, w, id)` tuple and uses their dtypes and converts them to tensorflow equivalents, and uses the shapes and dtypes to make a `tf.data.Dataset object`. Unles there is a workaround in this part for non-numpy objects, `make_iterator` would be a problem for `Mol` objects.

On a different note, `TextCNNTensorGraph` and `DTNNTensorGraph` now support `make_estimator`, so they can be crossed off the list.

**Comment by VIGS25** [comment] 2019-01-06 23:07
Here's the stack trace:
```Traceback (most recent call last):
  File "deepchem/test.py", line 303, in <module>
    test_weave_classification_estimator()
  File "deepchem/test.py", line 299, in test_weave_classification_estimator
    estimator.train(input_fn=lambda: input_fn(100))
  File "/home/vignesh/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/vignesh/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 809, in _train_model
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/home/vignesh/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 668, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/home/vignesh/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 760, in _call_input_fn
    return input_fn(**kwargs)
  File "deepchem/test.py", line 299, in <lambda>
    estimator.train(input_fn=lambda: input_fn(100))
  File "deepchem/test.py", line 278, in input_fn
    X, y, weights = dataset.make_iterator(64, epochs=epochs)
  File "/home/vignesh/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 294, in make_iterator
    dtypes = (tf.as_dtype(X.dtype), tf.as_dtype(y.dtype), tf.as_dtype(w.dtype))
AttributeError: 'WeaveMol' object has no attribute 'dtype' 
```

Here's the script to reproduce the error (Sorry a little long, but it contains the full definition of the Weave Model)

```
import numpy as np
import tensorflow as tf

import deepchem as dc
from deepchem.data import NumpyDataset
from deepchem.models import TensorGraph
from deepchem.molnet import load_bace_classification, load_delaney
from deepchem.models.tensorgraph.layers import ReduceSum, L2Loss, Dense, BatchNorm
from deepchem.models.tensorgraph.layers import Reshape, Label, Feature, Weights
from deepchem.models.tensorgraph.layers import SoftMaxCrossEntropy, SoftMax, WeightedError
from deepchem.models.tensorgraph.graph_layers import WeaveLayerFactory, WeaveGather
from deepchem.metrics import to_one_hot


class WeaveModel(TensorGraph):

  def __init__(self,
               n_tasks,
               n_atom_feat=75,
               n_pair_feat=14,
               n_hidden=50,
               n_graph_feat=128,
               mode="classification",
               n_classes=2,
               **kwargs):
    """
    Parameters
    ----------
    n_tasks: int
      Number of tasks
    n_atom_feat: int, optional
      Number of features per atom.
    n_pair_feat: int, optional
      Number of features per pair of atoms.
    n_hidden: int, optional
      Number of units(convolution depths) in corresponding hidden layer
    n_graph_feat: int, optional
      Number of output features for each molecule(graph)
    mode: str
      Either "classification" or "regression" for type of model.
    n_classes: int
      Number of classes to predict (only used in classification mode)
    """
    if mode not in ['classification', 'regression']:
      raise ValueError("mode must be either 'classification' or 'regression'")
    self.n_tasks = n_tasks
    self.n_atom_feat = n_atom_feat
    self.n_pair_feat = n_pair_feat
    self.n_hidden = n_hidden
    self.n_graph_feat = n_graph_feat
    self.mode = mode
    self.n_classes = n_classes
    super(WeaveModel, self).__init__(**kwargs)
    self.build_graph()

  def build_graph(self):
    """Building graph structures:
                Features => WeaveLayer => WeaveLayer => Dense => WeaveGather => Classification or Regression
                """
    self.atom_features = Feature(shape=(None, self.n_atom_feat))
    self.pair_features = Feature(shape=(None, self.n_pair_feat))
    self.pair_split = Feature(shape=(None,), dtype=tf.int32)
    self.atom_split = Feature(shape=(None,), dtype=tf.int32)
    self.atom_to_pair = Feature(shape=(None, 2), dtype=tf.int32)
    weave_layer1A, weave_layer1P = WeaveLayerFactory(
        n_atom_input_feat=self.n_atom_feat,
        n_pair_input_feat=self.n_pair_feat,
        n_atom_output_feat=self.n_hidden,
        n_pair_output_feat=self.n_hidden,
        in_layers=[
            self.atom_features, self.pair_features, self.pair_split,
            self.atom_to_pair
        ])
    weave_layer2A, weave_layer2P = WeaveLayerFactory(
        n_atom_input_feat=self.n_hidden,
        n_pair_input_feat=self.n_hidden,
        n_atom_output_feat=self.n_hidden,
        n_pair_output_feat=self.n_hidden,
        update_pair=False,
        in_layers=[
            weave_layer1A, weave_layer1P, self.pair_split, self.atom_to_pair
        ])
    dense1 = Dense(
        out_channels=self.n_graph_feat,
        activation_fn=tf.nn.tanh,
        in_layers=weave_layer2A)
    batch_norm1 = BatchNorm(epsilon=1e-5, in_layers=[dense1])
    weave_gather = WeaveGather(
        self.batch_size,
        n_input=self.n_graph_feat,
        gaussian_expand=True,
        in_layers=[batch_norm1, self.atom_split])

    n_tasks = self.n_tasks
    weights = Weights(shape=(None, n_tasks))
    if self.mode == 'classification':
      n_classes = self.n_classes
      labels = Label(shape=(None, n_tasks, n_classes))
      logits = Reshape(
          shape=(None, n_tasks, n_classes),
          in_layers=[
              Dense(in_layers=weave_gather, out_channels=n_tasks * n_classes)
          ])
      output = SoftMax(logits)
      self.add_output(output)
      loss = SoftMaxCrossEntropy(in_layers=[labels, logits])
      weighted_loss = WeightedError(in_layers=[loss, weights])
      self.set_loss(weighted_loss)
    else:
      labels = Label(shape=(None, n_tasks))
      output = Reshape(
          shape=(None, n_tasks),
          in_layers=[Dense(in_layers=weave_gather, out_channels=n_tasks)])
      self.add_output(output)
      weighted_loss = ReduceSum(L2Loss(in_layers=[labels, output, weights]))
      self.set_loss(weighted_loss)

  def compute_features_on_batch(self, X_b):
    """Computes the features for feed_dict.

    A tf.py_func wrapper is written around this when using the input_fn for make_estimator
    """

    atom_feat = []
    pair_feat = []
    atom_split = []
    atom_to_pair = []
    pair_split = []
    start = 0
    for im, mol in enumerate(X_b):
      n_atoms = mol.get_num_atoms()
      # number of atoms in each molecule
      atom_split.extend([im] * n_atoms)
      # index of pair features
      C0, C1 = np.meshgrid(np.arange(n_atoms), np.arange(n_atoms))
      atom_to_pair.append(
          np.transpose(np.array([C1.flatten() + start,
                                 C0.flatten() + start])))
      # number of pairs for each atom
      pair_split.extend(C1.flatten() + start)
      start = start + n_atoms

      # atom features
      atom_feat.append(mol.get_atom_features())
      # pair features
      pair_feat.append(
          np.reshape(mol.get_pair_features(),
                     (n_atoms * n_atoms, self.n_pair_feat)))

    atom_features = np.concatenate(atom_feat, axis=0)
    pair_features = np.concatenate(pair_feat, axis=0)
    pair_split = np.array(pair_split)
    atom_split = np.array(atom_split)
    atom_to_pair = np.concatenate(atom_to_pair, axis=0)

    return [atom_features, pair_features, pair_split, atom_split, atom_to_pair]

  def default_generator(self,
                        dataset,
                        epochs=1,
                        predict=False,
                        deterministic=True,
                        pad_batches=True):
    """TensorGraph style implementation """
    for epoch in range(epochs):
      for (X_b, y_b, w_b, ids_b) in dataset.iterbatches(
          batch_size=self.batch_size,
          deterministic=deterministic,
          pad_batches=pad_batches):

        feed_dict = dict()
        if y_b is not None:
          if self.mode == 'classification':
            feed_dict[self.labels[0]] = to_one_hot(y_b.flatten(),
                                                   self.n_classes).reshape(
                                                       -1, self.n_tasks,
                                                       self.n_classes)
          else:
            feed_dict[self.labels[0]] = y_b
        if w_b is not None:
          feed_dict[self.task_weights[0]] = w_b

        atom_feat = []
        pair_feat = []
        atom_split = []
        atom_to_pair = []
        pair_split = []
        start = 0
        for im, mol in enumerate(X_b):
          n_atoms = mol.get_num_atoms()
          # number of atoms in each molecule
          atom_split.extend([im] * n_atoms)
          # index of pair features
          C0, C1 = np.meshgrid(np.arange(n_atoms), np.arange(n_atoms))
          atom_to_pair.append(
              np.transpose(
                  np.array([C1.flatten() + start,
                            C0.flatten() + start])))
          # number of pairs for each atom
          pair_split.extend(C1.flatten() + start)
          start = start + n_atoms

          # atom features
          atom_feat.append(mol.get_atom_features())
          # pair features
          pair_feat.append(
              np.reshape(mol.get_pair_features(),
                         (n_atoms * n_atoms, self.n_pair_feat)))

        features = self.compute_features_on_batch(X_b)
        feed_dict[self.atom_features] = features[0]
        feed_dict[self.pair_features] = features[1]
        feed_dict[self.pair_split] = features[2]
        feed_dict[self.atom_split] = features[3]
        feed_dict[self.atom_to_pair] = features[4]
        yield feed_dict

  def create_estimator_inputs(self, feature_columns, weight_column, features,
                              labels, mode):
    tensors = dict()
    for layer, column in zip(self.features, feature_columns):
      feature_col = tf.feature_column.input_layer(features, [column])
      if column.dtype != feature_col.dtype:
        feature_col = tf.cast(feature_col, column.dtype)
      if len(column.shape) < 1:
        feature_col = tf.reshape(feature_col, shape=[tf.shape(feature_col)[0]])
      tensors[layer] = feature_col
    if weight_column is not None:
      tensors[self.task_weights[0]] = tf.feature_column.input_layer(
          features, [weight_column])
    if labels is not None:
      if self.mode == 'classification':
        tensors[self.labels[0]] = tf.one_hot(tf.cast(labels, tf.int32), 2)
      else:
        tensors[self.labels[0]] = labels

    return tensors


def get_dataset(mode='classification', featurizer='GraphConv', num_tasks=2):
  data_points = 10
  if mode == 'classification':
    tasks, all_dataset, transformers = load_bace_classification(featurizer)
  else:
    tasks, all_dataset, transformers = load_delaney(featurizer)

  train, valid, test = all_dataset
  for i in range(1, num_tasks):
    tasks.append("random_task")
  w = np.ones(shape=(data_points, len(tasks)))

  if mode == 'classification':
    y = np.random.randint(0, 2, size=(data_points, len(tasks)))
    metric = dc.metrics.Metric(
        dc.metrics.roc_auc_score, np.mean, mode="classification")
  else:
    y = np.random.normal(size=(data_points, len(tasks)))
    metric = dc.metrics.Metric(
        dc.metrics.mean_absolute_error, mode="regression")

  ds = NumpyDataset(train.X[:data_points], y, w, train.ids[:data_points])

  return tasks, ds, transformers, metric


def test_weave_classification_estimator():
  tasks, dataset, transformers, metric = get_dataset('classification', 'Weave')

  model = WeaveModel(len(tasks), mode='classification')
  dtypes = [tf.float32, tf.float32, tf.int32, tf.int32, tf.int32]

  def input_fn(epochs):
    X, y, weights = dataset.make_iterator(64, epochs=epochs)
    features = tf.py_func(model.compute_features_on_batch, [X], Tout=dtypes)
    feature_dict = dict()
    feature_dict['atom_features'] = features[0]
    feature_dict['pair_features'] = features[1]
    feature_dict['pair_split'] = features[2]
    feature_dict['atom_split'] = features[3]
    feature_dict['atom_to_pair'] = features[4]
    feature_dict['weights'] = weights

    return feature_dict, y

  atom_features = tf.feature_column.numeric_column(
      'atom_features', shape=(model.n_atom_feat,), dtype=dtypes[0])
  pair_features = tf.feature_column.numeric_column(
      'pair_features', shape=(model.n_pair_feat,), dtype=dtypes[1])
  pair_split = tf.feature_column.numeric_column(
      'pair_split', shape=(), dtype=dtypes[2])
  atom_split = tf.feature_column.numeric_column(
      'atom_split', shape=(), dtype=dtypes[3])
  atom_to_pair = tf.feature_column.numeric_column(
      'atom_to_pair', shape=(2,), dtype=dtypes[4])
  weight_col = tf.feature_column.numeric_column(
      'weights', shape=(model.n_tasks,))

  feature_columns = [
      atom_features, pair_features, pair_split, atom_split, atom_to_pair
  ]
  estimator = model.make_estimator(feature_columns, weight_col)
  estimator.train(input_fn=lambda: input_fn(100))


if __name__ == '__main__':
  test_weave_classification_estimator()
```

**Comment by VIGS25** [comment] 2019-01-08 19:56
I gave it a try, but realised that `tf.py_func` actually only works with `ndarray` and I had made a mistake when previously testing it with `non-ndarray`. 
There are no other Tensorflow wrapper functions, to the best of my knowledge that deal with objects that are not `ndarray`. So `make_estimator` won't work for the GraphModels except `DTNNModel`

**Comment by peastman** [comment] 2019-01-08 20:05
That makes sense.  @rbharath any thoughts on how to deal with this?

**Comment by VIGS25** [comment] 2019-01-08 20:15
One idea I had was if we could pass another argument called `map_fn` to the `dataset.make_iterator` function, that could do the feature extraction we want and then make the iterator on the new set of features. 

This `map_fn` can be used within the generator function for `dataset.make_iterator`. The generator operates over `dataset.iterbatches`. 

This would circumvent the need to use a `tf.py_func`, and bring us closer to `default_generator` since it both operate on `dataset.iterbatches` as well

**Comment by rbharath** [comment] 2020-04-01 18:44
Now that we've finished swapping over to Keras for all models, I think we can just use Keras's convert to estimator support. Additionally it looks like estimators are soft-deprecated in TF 2.X, with the docs encouraging direct use of Keras models in production.

I'm going to close this issue, but please let me know if we should re-open it

**Closed by rbharath** 2020-04-01 18:44 UTC
Labels: Contribution Welcome, Good Intermediate Contribution
