### ISSUE TITLE
PowerSign Optimizer

### ISSUE THREAD

**Issue by patrickhop** [deepchem/deepchem#1203] opened 2018-04-02 04:31 UTC
Google recently discovered some new optimizers using AutoML-style approaches. Would be fun to see how their PowerSign optimizer compares to Adam in our domain.

https://arxiv.org/pdf/1709.07417.pdf
https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/opt/PowerSignOptimizer

**Comment by lilleswing** [comment] 2018-04-05 16:47
More fun would be to reproduce the study over our graph based models and MoleculeNet datasets to see what a good optimizer is for Graph Based Molecular models.

Also it is interesting how this relates to population based training which essentially uses a genetic algorithm to determine optimal learning hyper-parameters.

**Comment by lilleswing** [comment] 2018-04-05 19:12
Drop in replacement and hyper-parameter scanning is a first pass scientific task though.

**Comment by patrickhop** [comment] 2018-04-05 22:07
Agreed. Do we have the statistical power to identify an increase in performance of like 1%? I assume that's what we're talking about here.

**Comment by abster12** [comment] 2018-04-16 21:11
Do I need to add the PowerSignOptimizer to the optimizer.py in deepchem to use it?

**Comment by peastman** [comment] 2018-04-24 17:53
I finally got around to reading the paper.  Very cool work.  I love this whole metalearning approach.  If deep learning works so well, then let's use it to figure out how to do deep learning better!

We should also add the linear cosine decay function they found.  That's already in Tensorflow (tf.train.linear_cosine_decay), so we can just wrap it in a new LearningRateSchedule subclass.

**Comment by abster12** [comment] 2018-04-24 17:56
Should I add it in the existing PR.

**Comment by peastman** [comment] 2018-04-24 18:03
Sure, if you want.

**Comment by patrickhop** [comment] 2018-04-25 21:19
before we close this, can someone run it on lipo or tox21? quite curious how this does.

**Comment by rbharath** [comment] 2018-07-20 13:09
Closing since optimizer has been implemented for some time

**Closed by rbharath** 2018-07-20 13:09 UTC
