### ISSUE TITLE
How to implement cross-validation for training set in deepchem?

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#736] opened 2017-08-07 18:18 UTC
Dear all,

I am wondering if there is a simple way to implement cross-validation for training set in deepchem. 

In Ski-kit learn, I can use 
"clf.fit(X,y)
 score = cross_val_score(clf, X, y, cv=20,scoring=kappa_scorer)" to calculate cross-validation score.

Could anyone show me how to do cross-validation in deepchem? A simple example would be great.

BTW, a quick question about obtaining predicted y value in deepchem. 

I defined a model, and fit with train)dataset as follows:  
"model.fit(train_dataset)
model.save()"

But how can I get y_pred? via model.predict(train_dataset)? I may miss something, but I didn't see that in example codes.

Thank you!
Cheng

**Comment by rbharath** [comment] 2017-08-07 19:32
For cross validation, you might want to look at the `Splitter.k_fold_split` function which splits a dataset k ways for cross validation. We don't however have a convenient version of `cross_val_score` but that might be a good utility to add. PRs welcome!

For `y_pred_valid`, you can use `model.predict(valid_dataset)`. I believe this is demonstrated in the IPython notebooks.

**Comment by chf42** [comment] 2017-08-07 20:00
Thank you much Bharath, I will take a look at Splitter.k_fold_split, and try cross-validation based on that.

**Comment by chf42** [comment] 2017-08-11 21:14
@rbharath I tried splitter.k_fold_split, but I met some errors:

 **k_datasets = splitter.k_fold_split(train_set,10,directories=None)
TypeError: k_fold_split() got an unexpected keyword argument 'directories'**

As such, I removed 'directories' from keywords, it still has errors: 
    **k_datasets = splitter.k_fold_split(train_set,10)
  File "deepchem_2.7/lib/python2.7/deepchem/splits/splitters.py", line 355, in k_fold_split
    if directories is None:
UnboundLocalError: local variable 'directories' referenced before assignment**

Would you mind show a correct way of using k_fold_split?

Thanks,
Cheng

**Comment by rbharath** [comment] 2017-08-11 21:31
The same commands are working for me:

```
In [2]: tox21_tasks, (train, valid, test), transformers = dc.molnet.load_tox21(featurizer="GraphConv")
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.

In [3]: splitter = dc.splits.RandomSplitter()

In [4]: splitter.k_fold_split(train, 4)
TIMING: dataset construction took 7.816 s
Loading dataset from disk.
TIMING: dataset construction took 12.473 s
Loading dataset from disk.
TIMING: dataset construction took 23.917 s
Loading dataset from disk.
TIMING: dataset construction took 8.549 s
Loading dataset from disk.
TIMING: dataset construction took 6.948 s
Loading dataset from disk.
TIMING: dataset construction took 10.759 s
Loading dataset from disk.
TIMING: dataset construction took 24.392 s
Loading dataset from disk.
3TIMING: dataset construction took 15.362 s
Loading dataset from disk.
TIMING: dataset construction took 5.113 s
Loading dataset from disk.
TIMING: dataset construction took 4.995 s
Loading dataset from disk.
TIMING: dataset construction took 23.746 s
Loading dataset from disk.
TIMING: dataset construction took 24.386 s
Loading dataset from disk.
TIMING: dataset construction took 4.049 s
Loading dataset from disk.
TIMING: dataset construction took 0.003 s
Loading dataset from disk.
TIMING: dataset construction took 27.489 s
Loading dataset from disk.
TIMING: dataset construction took 34.018 s
Loading dataset from disk.
Out[4]: 
[(<deepchem.data.datasets.DiskDataset at 0x7f17acbeaf10>,
  <deepchem.data.datasets.DiskDataset at 0x7f17f3cc6fd0>),
 (<deepchem.data.datasets.DiskDataset at 0x7f17abc22e50>,
  <deepchem.data.datasets.DiskDataset at 0x7f17f3c57350>),
 (<deepchem.data.datasets.DiskDataset at 0x7f17b5926f90>,
  <deepchem.data.datasets.DiskDataset at 0x7f17ad21b8d0>),
 (<deepchem.data.datasets.DiskDataset at 0x7f17aa7f5490>,
  <deepchem.data.datasets.DiskDataset at 0x7f17ac08be10>)]
```
Could you give these same commands a try?

**Comment by chf42** [comment] 2017-08-12 18:24
@rbharath Thank you! I tried the **splitter = dc.splits.RandomSplitter()**, followed by splitter.k_fold_split. It works well.
But, in my case, I used another **splitter = dc.splits.SingletaskStratifiedSplitter**(task_number=0, verbose=False); splitter.k_fold_split. Then, the error came out.

    k_splitter = splitter.k_fold_split(train,4)
  File "deepchem_2.7/lib/python2.7/deepchem/splits/splitters.py", line 355, in k_fold_split
    if directories is None:
UnboundLocalError: local variable 'directories' referenced before assignment

By the way, after I did k-fold splitter, splitter.k_fold_split, how could I get access to each subset? According to documents,  it returns "list of length k tuples of (train, cv)", **what is the difference between "train" and "cv"**? For example, **k_splitter = splitter.k_fold_split(train,4).** **k_splitter[0]** should give me **(train1,cv1)**. **k_splitter[0][0]** should give me **'train1'**. However, when I trained **model.fit(k_splitter[0][0])**, I have errors like "TypeError: 'NumpyDataset' object does not support indexing". However, I can run **model.fit(k_splitter[0])** successfully. I am very confused there... because I want to set up cross-validation for k-fold, I assume that I need to train 'train1' and predict 'cv1', and repeat until 'train k' and predict 'cv k'. 

Thanks,
Cheng

**Comment by rbharath** [comment] 2017-08-12 19:14
The commands are working for me with `SingletaskStratifiedSplitter`:

```
In [6]: splitter = dc.splits.SingletaskStratifiedSplitter()

In [7]: splitter.k_fold_split(train, 4)
TIMING: dataset construction took 7.125 s
Loading dataset from disk.
TIMING: dataset construction took 7.511 s
Loading dataset from disk.
TIMING: dataset construction took 7.562 s
Loading dataset from disk.
TIMING: dataset construction took 7.643 s
Loading dataset from disk.
Out[7]: 
[<deepchem.data.datasets.DiskDataset at 0x7f17ad480190>,
 <deepchem.data.datasets.DiskDataset at 0x7f17acf7c8d0>,
 <deepchem.data.datasets.DiskDataset at 0x7f17af477550>,
 <deepchem.data.datasets.DiskDataset at 0x7f17afcdc910>]
```

It looks like `SingletaskStratifiedSplitter` doesn't satisfy the new API, so I will create a new issue for this. This API mismatch might be causing your issues with `fit()`

**Comment by rbharath** [comment] 2018-02-26 14:32
Closing this issue. Feel free to re-open if necessary.

**Closed by rbharath** 2018-02-26 14:32 UTC

**Comment by filipm90** [comment] 2021-03-06 10:21
I could really use some help performing CV in combination with hyperparameter optimization. I am using HyperOpt package and implementation works fine, but I think that for loop in hyperopt_cv() where I use cv_splits (implementation of k_fold_split from DeepChem) just kills the performance. It would be useful having or finding a way how to use cross_val_score function to optimize this problem. Thanks!

`def hyperopt_cv(space):

    '''
    '''
    from hyperopt import STATUS_OK

    print('Params testing: ', space)
    mean_rms_score = []
    for train, val in tqdm(cv_splits):
        model = GraphConvModel(
                               n_tasks = len(tasks),
                               mode='regression',
                               seed=123,
                               model_dir=data_path,
                               **space
                              )

        model.fit(train)
        rms_score = model.evaluate(val, [metric], transformers)['mean-rms_score']
        mean_rms_score.append(rms_score)

    mean_rms_score = np.mean(mean_rms_score)
    print('Mean RMSE score:', mean_rms_score)
    sys.stdout.flush() 
    return {'loss': mean_rms_score, 'status': STATUS_OK, 'model': model}

def hyperopt_bp(max_evals=10):

    '''
    '''
    from hyperopt import fmin, tpe, Trials, space_eval

    trials = Trials()
    best_params = fmin(
                       fn=hyperopt_cv,
                       space=space,
                       algo=tpe.suggest,
                       max_evals=max_evals,
                       trials=trials,
		       rstate=np.random.RandomState(123)
                      )

    rms_score = trials.best_trial['result']['loss']
    print ('RMSE score:', rms_score)

    best_params = space_eval(space, best_params)

    print(f'Best parameters from 5-fold HyperOpt CV: {best_params}')
    return best_params`
