### ISSUE TITLE
Disallow pull requests with failed CI pipelines

### ISSUE THREAD

**Issue by vpohl** [deepchem/deepchem#2311] opened 2020-12-04 10:02 UTC
Hi there,

would it be possible that you require successful CI pipelines before merging to `master`? So that there is always a working current version of the repo.

This required check can be simply in the project settings, e.g.,
![101149036-a9c34e80-361e-11eb-8f76-d986fa70ecc0](https://user-images.githubusercontent.com/15653922/101150043-02dfb200-3620-11eb-8bb3-d6dcc850dee3.png)

**Comment by rbharath** [comment] 2020-12-04 17:36
@vpohl This is definitely a fair request! Our challenge is that often CI fails due to flaky numerical tests or downstream package updates that affect only a tiny portion of DeepChem. It hasn't seemed worth it to cut everything off for small errors in the past, but perhaps this needs to change now that the project is higher profile and has more users.

@peastman @ncfrey @nd-02110114 @seyonechithrananda (tagging in a few people off the top of my head, but please chime in if I've forgotten you here!) Do you folks think that enforcing status check passes is a good idea on future PRs given the state of our current CI infrastructure?

**Comment by peastman** [comment] 2020-12-04 17:41
I would also vote against this for the reasons you list.  For example, at this moment we have a test that just started failing on travis, but we haven't been able to reproduce the failure locally.  Tracking down the cause is a high priority, but I don't think we should block all other PRs from being merged while we do it.  This sort of thing happens frequently.

**Closed** 2021-10-19 23:34 UTC
